# Generated by Django 5.2 on 2025-05-07 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='tema',
        ),
        migrations.AddField(
            model_name='respuesta',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='foro.categoria'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Tema',
        ),
    ]
