# Generated by Django 5.2 on 2025-05-07 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0002_remove_respuesta_tema_respuesta_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='creado',
        ),
        migrations.AddField(
            model_name='respuesta',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foro.categoria'),
        ),
    ]
