# Generated by Django 5.2 on 2025-05-07 04:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0003_remove_respuesta_creado_respuesta_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
