# Generated by Django 5.2 on 2025-05-06 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
